name: Exam Cache Workflow

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  cache-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache pip
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-8578248

      # ✅ This is the required step — do not change the name
      - name: prime-cache-8578248
        run: echo "Cache result => ${{ steps.cache.outputs.cache-hit }}"
