name: Cache Python Dependencies

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Cache pip downloads
      - name: Cache pip
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-8578248

      - name: prime-cache-8578248
        run: echo "Cache result => ${{ steps.cache.outputs.cache-hit }}"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
